echo Creating virtual environment...
cd backend
python -m venv py_backend
echo Activating virtual environment...
.\py_backend\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt

echo Starting backend server...
python app.py

echo Starting frontend server...
cd ../frontend
npm run dev